name: Vigilancia Trenes

on:
  schedule:
    - cron: '*/20 * * * *'  # Revisión cada 20 minutos
    - cron: '0 8 * * *'     # 10:00 AM España (8:00 UTC)
    - cron: '0 20 * * *'    # 22:00 PM España (20:00 UTC)
  workflow_dispatch:        # Permite ejecutarlo manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install requests beautifulsoup4 pytz

      - name: Ejecutar Bot
        run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
